// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderStatus int32

const (
	OrderStatus_PENDING   OrderStatus = 0
	OrderStatus_SHIPPED   OrderStatus = 1
	OrderStatus_DELIVERED OrderStatus = 2
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "PENDING",
		1: "SHIPPED",
		2: "DELIVERED",
	}
	OrderStatus_value = map[string]int32{
		"PENDING":   0,
		"SHIPPED":   1,
		"DELIVERED": 2,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_api_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

type NotificationResponseType int32

const (
	NotificationResponseType_SUCCESS NotificationResponseType = 0
	NotificationResponseType_FAILURE NotificationResponseType = 1
)

// Enum value maps for NotificationResponseType.
var (
	NotificationResponseType_name = map[int32]string{
		0: "SUCCESS",
		1: "FAILURE",
	}
	NotificationResponseType_value = map[string]int32{
		"SUCCESS": 0,
		"FAILURE": 1,
	}
)

func (x NotificationResponseType) Enum() *NotificationResponseType {
	p := new(NotificationResponseType)
	*p = x
	return p
}

func (x NotificationResponseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationResponseType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_enumTypes[1].Descriptor()
}

func (NotificationResponseType) Type() protoreflect.EnumType {
	return &file_api_proto_enumTypes[1]
}

func (x NotificationResponseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationResponseType.Descriptor instead.
func (NotificationResponseType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

type ProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Rating        int64                  `protobuf:"varint,6,opt,name=rating,proto3" json:"rating,omitempty"`
	NumReviews    int64                  `protobuf:"varint,7,opt,name=num_reviews,json=numReviews,proto3" json:"num_reviews,omitempty"`
	Price         float32                `protobuf:"fixed32,8,opt,name=price,proto3" json:"price,omitempty"`
	CountInStock  int64                  `protobuf:"varint,9,opt,name=count_in_stock,json=countInStock,proto3" json:"count_in_stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductReq) Reset() {
	*x = ProductReq{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductReq) ProtoMessage() {}

func (x *ProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductReq.ProtoReflect.Descriptor instead.
func (*ProductReq) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *ProductReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductReq) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ProductReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ProductReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductReq) GetRating() int64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *ProductReq) GetNumReviews() int64 {
	if x != nil {
		return x.NumReviews
	}
	return 0
}

func (x *ProductReq) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductReq) GetCountInStock() int64 {
	if x != nil {
		return x.CountInStock
	}
	return 0
}

type ProductRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Rating        int64                  `protobuf:"varint,6,opt,name=rating,proto3" json:"rating,omitempty"`
	NumReviews    int64                  `protobuf:"varint,7,opt,name=num_reviews,json=numReviews,proto3" json:"num_reviews,omitempty"`
	Price         float32                `protobuf:"fixed32,8,opt,name=price,proto3" json:"price,omitempty"`
	CountInStock  int64                  `protobuf:"varint,9,opt,name=count_in_stock,json=countInStock,proto3" json:"count_in_stock,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductRes) Reset() {
	*x = ProductRes{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductRes) ProtoMessage() {}

func (x *ProductRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductRes.ProtoReflect.Descriptor instead.
func (*ProductRes) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *ProductRes) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductRes) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ProductRes) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ProductRes) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductRes) GetRating() int64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *ProductRes) GetNumReviews() int64 {
	if x != nil {
		return x.NumReviews
	}
	return 0
}

func (x *ProductRes) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductRes) GetCountInStock() int64 {
	if x != nil {
		return x.CountInStock
	}
	return 0
}

func (x *ProductRes) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ProductRes) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListProductRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*ProductRes          `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductRes) Reset() {
	*x = ListProductRes{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductRes) ProtoMessage() {}

func (x *ListProductRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductRes.ProtoReflect.Descriptor instead.
func (*ListProductRes) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *ListProductRes) GetProducts() []*ProductRes {
	if x != nil {
		return x.Products
	}
	return nil
}

type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Quantity      int64                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Price         float32                `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	ProductId     int64                  `protobuf:"varint,5,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *OrderItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderItem) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItem) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *OrderItem) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderItem) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type OrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Items         []*OrderItem           `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,3,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	TaxPrice      float32                `protobuf:"fixed32,4,opt,name=tax_price,json=taxPrice,proto3" json:"tax_price,omitempty"`
	ShippingPrice float32                `protobuf:"fixed32,5,opt,name=shipping_price,json=shippingPrice,proto3" json:"shipping_price,omitempty"`
	TotalPrice    float32                `protobuf:"fixed32,6,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	UserId        int64                  `protobuf:"varint,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserEmail     string                 `protobuf:"bytes,8,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	Status        OrderStatus            `protobuf:"varint,9,opt,name=status,proto3,enum=pb.OrderStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderReq) Reset() {
	*x = OrderReq{}
	mi := &file_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderReq) ProtoMessage() {}

func (x *OrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderReq.ProtoReflect.Descriptor instead.
func (*OrderReq) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *OrderReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderReq) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *OrderReq) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *OrderReq) GetTaxPrice() float32 {
	if x != nil {
		return x.TaxPrice
	}
	return 0
}

func (x *OrderReq) GetShippingPrice() float32 {
	if x != nil {
		return x.ShippingPrice
	}
	return 0
}

func (x *OrderReq) GetTotalPrice() float32 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *OrderReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderReq) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *OrderReq) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_PENDING
}

type OrderRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Items         []*OrderItem           `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,3,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	TaxPrice      float32                `protobuf:"fixed32,4,opt,name=tax_price,json=taxPrice,proto3" json:"tax_price,omitempty"`
	ShippingPrice float32                `protobuf:"fixed32,5,opt,name=shipping_price,json=shippingPrice,proto3" json:"shipping_price,omitempty"`
	TotalPrice    float32                `protobuf:"fixed32,6,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	UserId        int64                  `protobuf:"varint,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Staus         OrderStatus            `protobuf:"varint,10,opt,name=staus,proto3,enum=pb.OrderStatus" json:"staus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderRes) Reset() {
	*x = OrderRes{}
	mi := &file_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderRes) ProtoMessage() {}

func (x *OrderRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderRes.ProtoReflect.Descriptor instead.
func (*OrderRes) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

func (x *OrderRes) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderRes) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *OrderRes) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *OrderRes) GetTaxPrice() float32 {
	if x != nil {
		return x.TaxPrice
	}
	return 0
}

func (x *OrderRes) GetShippingPrice() float32 {
	if x != nil {
		return x.ShippingPrice
	}
	return 0
}

func (x *OrderRes) GetTotalPrice() float32 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *OrderRes) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderRes) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *OrderRes) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *OrderRes) GetStaus() OrderStatus {
	if x != nil {
		return x.Staus
	}
	return OrderStatus_PENDING
}

type ListOrderRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*OrderRes            `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrderRes) Reset() {
	*x = ListOrderRes{}
	mi := &file_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderRes) ProtoMessage() {}

func (x *ListOrderRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderRes.ProtoReflect.Descriptor instead.
func (*ListOrderRes) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{6}
}

func (x *ListOrderRes) GetOrders() []*OrderRes {
	if x != nil {
		return x.Orders
	}
	return nil
}

type UserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	IsAdmin       bool                   `protobuf:"varint,5,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserReq) Reset() {
	*x = UserReq{}
	mi := &file_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReq) ProtoMessage() {}

func (x *UserReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReq.ProtoReflect.Descriptor instead.
func (*UserReq) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{7}
}

func (x *UserReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserReq) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

type UserRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	IsAdmin       bool                   `protobuf:"varint,5,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRes) Reset() {
	*x = UserRes{}
	mi := &file_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRes) ProtoMessage() {}

func (x *UserRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRes.ProtoReflect.Descriptor instead.
func (*UserRes) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{8}
}

func (x *UserRes) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserRes) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserRes) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserRes) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *UserRes) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListUserRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserRes             `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserRes) Reset() {
	*x = ListUserRes{}
	mi := &file_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserRes) ProtoMessage() {}

func (x *ListUserRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserRes.ProtoReflect.Descriptor instead.
func (*ListUserRes) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{9}
}

func (x *ListUserRes) GetUsers() []*UserRes {
	if x != nil {
		return x.Users
	}
	return nil
}

type SessionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserEmail     string                 `protobuf:"bytes,2,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	IsRevoked     bool                   `protobuf:"varint,4,opt,name=is_revoked,json=isRevoked,proto3" json:"is_revoked,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionReq) Reset() {
	*x = SessionReq{}
	mi := &file_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionReq) ProtoMessage() {}

func (x *SessionReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionReq.ProtoReflect.Descriptor instead.
func (*SessionReq) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{10}
}

func (x *SessionReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SessionReq) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *SessionReq) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *SessionReq) GetIsRevoked() bool {
	if x != nil {
		return x.IsRevoked
	}
	return false
}

func (x *SessionReq) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type SessionRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserEmail     string                 `protobuf:"bytes,2,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	IsRevoked     bool                   `protobuf:"varint,4,opt,name=is_revoked,json=isRevoked,proto3" json:"is_revoked,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionRes) Reset() {
	*x = SessionRes{}
	mi := &file_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRes) ProtoMessage() {}

func (x *SessionRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRes.ProtoReflect.Descriptor instead.
func (*SessionRes) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{11}
}

func (x *SessionRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SessionRes) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *SessionRes) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *SessionRes) GetIsRevoked() bool {
	if x != nil {
		return x.IsRevoked
	}
	return false
}

func (x *SessionRes) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type NotificationEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserEmail     string                 `protobuf:"bytes,2,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	OrderStatus   OrderStatus            `protobuf:"varint,3,opt,name=order_status,json=orderStatus,proto3,enum=pb.OrderStatus" json:"order_status,omitempty"`
	OrderId       int64                  `protobuf:"varint,4,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	StateId       int64                  `protobuf:"varint,5,opt,name=state_id,json=stateId,proto3" json:"state_id,omitempty"`
	Attempts      int64                  `protobuf:"varint,6,opt,name=attempts,proto3" json:"attempts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationEvent) Reset() {
	*x = NotificationEvent{}
	mi := &file_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationEvent) ProtoMessage() {}

func (x *NotificationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationEvent.ProtoReflect.Descriptor instead.
func (*NotificationEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{12}
}

func (x *NotificationEvent) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NotificationEvent) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *NotificationEvent) GetOrderStatus() OrderStatus {
	if x != nil {
		return x.OrderStatus
	}
	return OrderStatus_PENDING
}

func (x *NotificationEvent) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *NotificationEvent) GetStateId() int64 {
	if x != nil {
		return x.StateId
	}
	return 0
}

func (x *NotificationEvent) GetAttempts() int64 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

type ListNotificationEventsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationEventsReq) Reset() {
	*x = ListNotificationEventsReq{}
	mi := &file_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationEventsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationEventsReq) ProtoMessage() {}

func (x *ListNotificationEventsReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationEventsReq.ProtoReflect.Descriptor instead.
func (*ListNotificationEventsReq) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{13}
}

type ListNotificationEventsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*NotificationEvent   `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationEventsRes) Reset() {
	*x = ListNotificationEventsRes{}
	mi := &file_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationEventsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationEventsRes) ProtoMessage() {}

func (x *ListNotificationEventsRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationEventsRes.ProtoReflect.Descriptor instead.
func (*ListNotificationEventsRes) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{14}
}

func (x *ListNotificationEventsRes) GetEvents() []*NotificationEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type UpdateNotificationEventReq struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Id            int64                    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StateId       int64                    `protobuf:"varint,2,opt,name=state_id,json=stateId,proto3" json:"state_id,omitempty"`
	OrderId       int64                    `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ResponseType  NotificationResponseType `protobuf:"varint,4,opt,name=response_type,json=responseType,proto3,enum=pb.NotificationResponseType" json:"response_type,omitempty"`
	Message       string                   `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNotificationEventReq) Reset() {
	*x = UpdateNotificationEventReq{}
	mi := &file_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNotificationEventReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotificationEventReq) ProtoMessage() {}

func (x *UpdateNotificationEventReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotificationEventReq.ProtoReflect.Descriptor instead.
func (*UpdateNotificationEventReq) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateNotificationEventReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateNotificationEventReq) GetStateId() int64 {
	if x != nil {
		return x.StateId
	}
	return 0
}

func (x *UpdateNotificationEventReq) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *UpdateNotificationEventReq) GetResponseType() NotificationResponseType {
	if x != nil {
		return x.ResponseType
	}
	return NotificationResponseType_SUCCESS
}

func (x *UpdateNotificationEventReq) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateNotificationEventRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Succeeded     bool                   `protobuf:"varint,1,opt,name=succeeded,proto3" json:"succeeded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNotificationEventRes) Reset() {
	*x = UpdateNotificationEventRes{}
	mi := &file_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNotificationEventRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotificationEventRes) ProtoMessage() {}

func (x *UpdateNotificationEventRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotificationEventRes.ProtoReflect.Descriptor instead.
func (*UpdateNotificationEventRes) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateNotificationEventRes) GetSucceeded() bool {
	if x != nil {
		return x.Succeeded
	}
	return false
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf9\x01\n" +
	"\n" +
	"ProductReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x16\n" +
	"\x06rating\x18\x06 \x01(\x03R\x06rating\x12\x1f\n" +
	"\vnum_reviews\x18\a \x01(\x03R\n" +
	"numReviews\x12\x14\n" +
	"\x05price\x18\b \x01(\x02R\x05price\x12$\n" +
	"\x0ecount_in_stock\x18\t \x01(\x03R\fcountInStock\"\xef\x02\n" +
	"\n" +
	"ProductRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x16\n" +
	"\x06rating\x18\x06 \x01(\x03R\x06rating\x12\x1f\n" +
	"\vnum_reviews\x18\a \x01(\x03R\n" +
	"numReviews\x12\x14\n" +
	"\x05price\x18\b \x01(\x02R\x05price\x12$\n" +
	"\x0ecount_in_stock\x18\t \x01(\x03R\fcountInStock\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"<\n" +
	"\x0eListProductRes\x12*\n" +
	"\bproducts\x18\x01 \x03(\v2\x0e.pb.ProductResR\bproducts\"\x86\x01\n" +
	"\tOrderItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x03R\bquantity\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x02R\x05price\x12\x1d\n" +
	"\n" +
	"product_id\x18\x05 \x01(\x03R\tproductId\"\xac\x02\n" +
	"\bOrderReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12#\n" +
	"\x05items\x18\x02 \x03(\v2\r.pb.OrderItemR\x05items\x12%\n" +
	"\x0epayment_method\x18\x03 \x01(\tR\rpaymentMethod\x12\x1b\n" +
	"\ttax_price\x18\x04 \x01(\x02R\btaxPrice\x12%\n" +
	"\x0eshipping_price\x18\x05 \x01(\x02R\rshippingPrice\x12\x1f\n" +
	"\vtotal_price\x18\x06 \x01(\x02R\n" +
	"totalPrice\x12\x17\n" +
	"\auser_id\x18\a \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"user_email\x18\b \x01(\tR\tuserEmail\x12'\n" +
	"\x06status\x18\t \x01(\x0e2\x0f.pb.OrderStatusR\x06status\"\x81\x03\n" +
	"\bOrderRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12#\n" +
	"\x05items\x18\x02 \x03(\v2\r.pb.OrderItemR\x05items\x12%\n" +
	"\x0epayment_method\x18\x03 \x01(\tR\rpaymentMethod\x12\x1b\n" +
	"\ttax_price\x18\x04 \x01(\x02R\btaxPrice\x12%\n" +
	"\x0eshipping_price\x18\x05 \x01(\x02R\rshippingPrice\x12\x1f\n" +
	"\vtotal_price\x18\x06 \x01(\x02R\n" +
	"totalPrice\x12\x17\n" +
	"\auser_id\x18\a \x01(\x03R\x06userId\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12%\n" +
	"\x05staus\x18\n" +
	" \x01(\x0e2\x0f.pb.OrderStatusR\x05staus\"4\n" +
	"\fListOrderRes\x12$\n" +
	"\x06orders\x18\x01 \x03(\v2\f.pb.OrderResR\x06orders\"z\n" +
	"\aUserReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x19\n" +
	"\bis_admin\x18\x05 \x01(\bR\aisAdmin\"\xb5\x01\n" +
	"\aUserRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x19\n" +
	"\bis_admin\x18\x05 \x01(\bR\aisAdmin\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"0\n" +
	"\vListUserRes\x12!\n" +
	"\x05users\x18\x01 \x03(\v2\v.pb.UserResR\x05users\"\xba\x01\n" +
	"\n" +
	"SessionReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"user_email\x18\x02 \x01(\tR\tuserEmail\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"is_revoked\x18\x04 \x01(\bR\tisRevoked\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\xba\x01\n" +
	"\n" +
	"SessionRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"user_email\x18\x02 \x01(\tR\tuserEmail\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"is_revoked\x18\x04 \x01(\bR\tisRevoked\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\xc8\x01\n" +
	"\x11NotificationEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"user_email\x18\x02 \x01(\tR\tuserEmail\x122\n" +
	"\forder_status\x18\x03 \x01(\x0e2\x0f.pb.OrderStatusR\vorderStatus\x12\x19\n" +
	"\border_id\x18\x04 \x01(\x03R\aorderId\x12\x19\n" +
	"\bstate_id\x18\x05 \x01(\x03R\astateId\x12\x1a\n" +
	"\battempts\x18\x06 \x01(\x03R\battempts\"\x1b\n" +
	"\x19ListNotificationEventsReq\"J\n" +
	"\x19ListNotificationEventsRes\x12-\n" +
	"\x06events\x18\x01 \x03(\v2\x15.pb.NotificationEventR\x06events\"\xbf\x01\n" +
	"\x1aUpdateNotificationEventReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bstate_id\x18\x02 \x01(\x03R\astateId\x12\x19\n" +
	"\border_id\x18\x03 \x01(\x03R\aorderId\x12A\n" +
	"\rresponse_type\x18\x04 \x01(\x0e2\x1c.pb.NotificationResponseTypeR\fresponseType\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\":\n" +
	"\x1aUpdateNotificationEventRes\x12\x1c\n" +
	"\tsucceeded\x18\x01 \x01(\bR\tsucceeded*6\n" +
	"\vOrderStatus\x12\v\n" +
	"\aPENDING\x10\x00\x12\v\n" +
	"\aSHIPPED\x10\x01\x12\r\n" +
	"\tDELIVERED\x10\x02*4\n" +
	"\x18NotificationResponseType\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\v\n" +
	"\aFAILURE\x10\x012\x88\a\n" +
	"\x05ecomm\x121\n" +
	"\rCreateProduct\x12\x0e.pb.ProductReq\x1a\x0e.pb.ProductRes\"\x00\x12.\n" +
	"\n" +
	"GetProduct\x12\x0e.pb.ProductReq\x1a\x0e.pb.ProductRes\"\x00\x124\n" +
	"\fListProducts\x12\x0e.pb.ProductReq\x1a\x12.pb.ListProductRes\"\x00\x121\n" +
	"\rUpdateProduct\x12\x0e.pb.ProductReq\x1a\x0e.pb.ProductRes\"\x00\x121\n" +
	"\rDeleteProduct\x12\x0e.pb.ProductReq\x1a\x0e.pb.ProductRes\"\x00\x12+\n" +
	"\vCreateOrder\x12\f.pb.OrderReq\x1a\f.pb.OrderRes\"\x00\x12(\n" +
	"\bGetOrder\x12\f.pb.OrderReq\x1a\f.pb.OrderRes\"\x00\x12.\n" +
	"\n" +
	"ListOrders\x12\f.pb.OrderReq\x1a\x10.pb.ListOrderRes\"\x00\x121\n" +
	"\x11UpdateOrderStatus\x12\f.pb.OrderReq\x1a\f.pb.OrderRes\"\x00\x12+\n" +
	"\vDeleteOrder\x12\f.pb.OrderReq\x1a\f.pb.OrderRes\"\x00\x12(\n" +
	"\n" +
	"CreateUser\x12\v.pb.UserReq\x1a\v.pb.UserRes\"\x00\x12%\n" +
	"\aGetUser\x12\v.pb.UserReq\x1a\v.pb.UserRes\"\x00\x12+\n" +
	"\tListUsers\x12\v.pb.UserReq\x1a\x0f.pb.ListUserRes\"\x00\x12(\n" +
	"\n" +
	"UpdateUser\x12\v.pb.UserReq\x1a\v.pb.UserRes\"\x00\x12(\n" +
	"\n" +
	"DeleteUser\x12\v.pb.UserReq\x1a\v.pb.UserRes\"\x00\x121\n" +
	"\rCreateSession\x12\x0e.pb.SessionReq\x1a\x0e.pb.SessionRes\"\x00\x12.\n" +
	"\n" +
	"GetSession\x12\x0e.pb.SessionReq\x1a\x0e.pb.SessionRes\"\x00\x121\n" +
	"\rRevokeSession\x12\x0e.pb.SessionReq\x1a\x0e.pb.SessionRes\"\x00\x121\n" +
	"\rDeleteSession\x12\x0e.pb.SessionReq\x1a\x0e.pb.SessionRes\"\x00B%Z#github.com/dhij/ecomm/ecomm-grpc/pbb\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_api_proto_goTypes = []any{
	(OrderStatus)(0),                   // 0: pb.OrderStatus
	(NotificationResponseType)(0),      // 1: pb.NotificationResponseType
	(*ProductReq)(nil),                 // 2: pb.ProductReq
	(*ProductRes)(nil),                 // 3: pb.ProductRes
	(*ListProductRes)(nil),             // 4: pb.ListProductRes
	(*OrderItem)(nil),                  // 5: pb.OrderItem
	(*OrderReq)(nil),                   // 6: pb.OrderReq
	(*OrderRes)(nil),                   // 7: pb.OrderRes
	(*ListOrderRes)(nil),               // 8: pb.ListOrderRes
	(*UserReq)(nil),                    // 9: pb.UserReq
	(*UserRes)(nil),                    // 10: pb.UserRes
	(*ListUserRes)(nil),                // 11: pb.ListUserRes
	(*SessionReq)(nil),                 // 12: pb.SessionReq
	(*SessionRes)(nil),                 // 13: pb.SessionRes
	(*NotificationEvent)(nil),          // 14: pb.NotificationEvent
	(*ListNotificationEventsReq)(nil),  // 15: pb.ListNotificationEventsReq
	(*ListNotificationEventsRes)(nil),  // 16: pb.ListNotificationEventsRes
	(*UpdateNotificationEventReq)(nil), // 17: pb.UpdateNotificationEventReq
	(*UpdateNotificationEventRes)(nil), // 18: pb.UpdateNotificationEventRes
	(*timestamppb.Timestamp)(nil),      // 19: google.protobuf.Timestamp
}
var file_api_proto_depIdxs = []int32{
	19, // 0: pb.ProductRes.created_at:type_name -> google.protobuf.Timestamp
	19, // 1: pb.ProductRes.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 2: pb.ListProductRes.products:type_name -> pb.ProductRes
	5,  // 3: pb.OrderReq.items:type_name -> pb.OrderItem
	0,  // 4: pb.OrderReq.status:type_name -> pb.OrderStatus
	5,  // 5: pb.OrderRes.items:type_name -> pb.OrderItem
	19, // 6: pb.OrderRes.created_at:type_name -> google.protobuf.Timestamp
	19, // 7: pb.OrderRes.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 8: pb.OrderRes.staus:type_name -> pb.OrderStatus
	7,  // 9: pb.ListOrderRes.orders:type_name -> pb.OrderRes
	19, // 10: pb.UserRes.created_at:type_name -> google.protobuf.Timestamp
	10, // 11: pb.ListUserRes.users:type_name -> pb.UserRes
	19, // 12: pb.SessionReq.expires_at:type_name -> google.protobuf.Timestamp
	19, // 13: pb.SessionRes.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 14: pb.NotificationEvent.order_status:type_name -> pb.OrderStatus
	14, // 15: pb.ListNotificationEventsRes.events:type_name -> pb.NotificationEvent
	1,  // 16: pb.UpdateNotificationEventReq.response_type:type_name -> pb.NotificationResponseType
	2,  // 17: pb.ecomm.CreateProduct:input_type -> pb.ProductReq
	2,  // 18: pb.ecomm.GetProduct:input_type -> pb.ProductReq
	2,  // 19: pb.ecomm.ListProducts:input_type -> pb.ProductReq
	2,  // 20: pb.ecomm.UpdateProduct:input_type -> pb.ProductReq
	2,  // 21: pb.ecomm.DeleteProduct:input_type -> pb.ProductReq
	6,  // 22: pb.ecomm.CreateOrder:input_type -> pb.OrderReq
	6,  // 23: pb.ecomm.GetOrder:input_type -> pb.OrderReq
	6,  // 24: pb.ecomm.ListOrders:input_type -> pb.OrderReq
	6,  // 25: pb.ecomm.UpdateOrderStatus:input_type -> pb.OrderReq
	6,  // 26: pb.ecomm.DeleteOrder:input_type -> pb.OrderReq
	9,  // 27: pb.ecomm.CreateUser:input_type -> pb.UserReq
	9,  // 28: pb.ecomm.GetUser:input_type -> pb.UserReq
	9,  // 29: pb.ecomm.ListUsers:input_type -> pb.UserReq
	9,  // 30: pb.ecomm.UpdateUser:input_type -> pb.UserReq
	9,  // 31: pb.ecomm.DeleteUser:input_type -> pb.UserReq
	12, // 32: pb.ecomm.CreateSession:input_type -> pb.SessionReq
	12, // 33: pb.ecomm.GetSession:input_type -> pb.SessionReq
	12, // 34: pb.ecomm.RevokeSession:input_type -> pb.SessionReq
	12, // 35: pb.ecomm.DeleteSession:input_type -> pb.SessionReq
	3,  // 36: pb.ecomm.CreateProduct:output_type -> pb.ProductRes
	3,  // 37: pb.ecomm.GetProduct:output_type -> pb.ProductRes
	4,  // 38: pb.ecomm.ListProducts:output_type -> pb.ListProductRes
	3,  // 39: pb.ecomm.UpdateProduct:output_type -> pb.ProductRes
	3,  // 40: pb.ecomm.DeleteProduct:output_type -> pb.ProductRes
	7,  // 41: pb.ecomm.CreateOrder:output_type -> pb.OrderRes
	7,  // 42: pb.ecomm.GetOrder:output_type -> pb.OrderRes
	8,  // 43: pb.ecomm.ListOrders:output_type -> pb.ListOrderRes
	7,  // 44: pb.ecomm.UpdateOrderStatus:output_type -> pb.OrderRes
	7,  // 45: pb.ecomm.DeleteOrder:output_type -> pb.OrderRes
	10, // 46: pb.ecomm.CreateUser:output_type -> pb.UserRes
	10, // 47: pb.ecomm.GetUser:output_type -> pb.UserRes
	11, // 48: pb.ecomm.ListUsers:output_type -> pb.ListUserRes
	10, // 49: pb.ecomm.UpdateUser:output_type -> pb.UserRes
	10, // 50: pb.ecomm.DeleteUser:output_type -> pb.UserRes
	13, // 51: pb.ecomm.CreateSession:output_type -> pb.SessionRes
	13, // 52: pb.ecomm.GetSession:output_type -> pb.SessionRes
	13, // 53: pb.ecomm.RevokeSession:output_type -> pb.SessionRes
	13, // 54: pb.ecomm.DeleteSession:output_type -> pb.SessionRes
	36, // [36:55] is the sub-list for method output_type
	17, // [17:36] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		EnumInfos:         file_api_proto_enumTypes,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
