package main

func main() {
	// goroutines.JobQueueSample()
	// goroutines.MultpleProducersOneConsumerPattern()
	// goroutines.GracefulShutdownSample()
	// goroutines.RealTimeChatServer()
	// goroutines.SelectSample()
	// goroutines.SelectMultiplexing()
	// goroutines.TimeOutAndDeadliens()
	// goroutines.CancellationAndTimeout()
	// goroutines.HeartBeatSample()
	// goroutines.FanOutDistrubuteSample()
	// goroutines.ContextCancellationExample()
	// goroutines.FanOutFanInWithContext()
	// goroutines.WaitGroupSampleOne()
	// goroutines.WaitingForMultipleGoRoutinesToFinish()
	// goroutines.WgProcessMultipleFileExample()
	// goroutines.GoroutineswithChannelsAndWaitGroup()
	// goroutines.ReadingFileSample()
	// goroutines.WritingFileSample()
	// goroutines.CopyFromReadertoWriter()
	// goroutines.CustomReaderSample()
	// goroutines.CustomHelloReaderSample()
	// goroutines.ReadPartialContentFromString()
	// goroutines.MultiReaderSample()
	// goroutines.MultiWriterSample()
	// goroutines.TeeeReaderSampleTwo()
	// goroutines.RedirectStdoutToAFile()
	// goroutines.Uint8Sample()
	// goroutines.ByteSample()
	// goroutines.BufferEncodeSample()
	// goroutines.LimitReaderSample()
	// goroutines.MapSampleOne()
	// goroutines.MapDeclaringAndUsing()
	// goroutines.MapOfStructs()
	// goroutines.MapOfSlices()
	// goroutines.SortingAMap()
	// goroutines.MapWithInterface()
	// goroutines.ConcurrencySafeMap()
	// goroutines.MapWithLock()
	// goroutines.CountingFrequency()
	// goroutines.BasicMapLoop()

	// goroutines.BasicEventLoopStyleUsingSelect()
	// goroutines.ConcurrentTaskQueue()
	// goroutines.MessageQueueSystem()
	// goroutines.ManualContextTimeout()
	// goroutines.GoRoutineDebugging()
	// goroutines.SimpleTCPServer()
	// goroutines.GoRoutinesFanOutFanIn()
	// goroutines.TimeoutUsingSelect()
	// goroutines.InterfaceExample()

	// goroutines.MiniRuntimeProgram()

	// goroutines.SortSample()

	// goroutines.SliceSampleOne()

	// fundamentals.StringVsPointerStringTwo()

	// goroutines.ContextTimeoutExplain()
	// goroutines.ContextWithValueExplain()

	// http.HandleFunc("/hello", goroutines.HelloHandler)
	// http.ListenAndServe(":8000", nil)
}
